/** Service-role access only. Mounted behind adminProcedure; no auth-schema REST joins. */
export function createStoryModeration(db:any){
 const checked=(result:any)=>{if(result.error)throw new Error('Story moderation data could not be loaded. Please retry.');return result.data||[]};
 async function all(make:()=>any){const rows:any[]=[];for(let offset=0;;offset+=500){const batch=checked(await make().range(offset,offset+499));rows.push(...batch);if(batch.length<500)return rows;}}
 async function reports(){return all(()=>db.from('story_reports').select('id,story_id,reporter_user_id,reason,created_at').order('created_at',{ascending:false}));}
 async function related(table:string,fields:string,key:string,ids:string[]){const rows:any[]=[];for(let i=0;i<ids.length;i+=100)rows.push(...await all(()=>db.from(table).select(fields).in(key,ids.slice(i,i+100))));return rows;}
 async function enrich(rows:any[],reportRows?:any[]){if(!rows.length)return[];const ids=rows.map(r=>r.id);const [places,profiles,r]=await Promise.all([related('places','id,name','id',[...new Set(rows.map(r=>r.place_id))]),related('profiles','user_id,display_name,username','user_id',[...new Set(rows.map(r=>r.user_id).filter(Boolean))]),reportRows?Promise.resolve(reportRows):related('story_reports','id,story_id','story_id',ids)]);return rows.map(row=>({...row,place_name:places.find(p=>p.id===row.place_id)?.name,user_name:profiles.find(p=>p.user_id===row.user_id)?.display_name||'Tavvy member',report_count:r.filter(report=>report.story_id===row.id).length}));}
 async function getStories(limit=50,offset=0,status?:string,hasReports?:boolean):Promise<{stories:any[];total:number}>{
  limit=Math.max(1,Math.min(100,limit));offset=Math.max(0,offset);
  if(hasReports){const reportRows=await reports();const ids=[...new Set(reportRows.map(r=>r.story_id))];const rows=(await related('place_stories','*','id',ids)).filter(r=>!status||r.status===status).sort((a,b)=>b.created_at.localeCompare(a.created_at)||b.id.localeCompare(a.id));return{stories:await enrich(rows.slice(offset,offset+limit),reportRows),total:rows.length};}
  let query=db.from('place_stories').select('*',{count:'exact'});if(status)query=query.eq('status',status);const result=await query.order('created_at',{ascending:false}).order('id',{ascending:false}).range(offset,offset+limit-1);return{stories:await enrich(checked(result)),total:result.count||0};
 }
 async function getStoryById(id:string){const result=await db.from('place_stories').select('*').eq('id',id).maybeSingle();checked(result);return result.data?(await enrich([result.data]))[0]:null;}
 async function getStoryReports(id:string){const rows=await all(()=>db.from('story_reports').select('id,story_id,reporter_user_id,reason,created_at').eq('story_id',id).order('created_at',{ascending:false}));const profiles=await related('profiles','user_id,display_name,username','user_id',[...new Set(rows.map(r=>r.reporter_user_id))]);return rows.map(row=>({...row,reporter_name:profiles.find(p=>p.user_id===row.reporter_user_id)?.display_name||'Tavvy member'}));}
 async function getStoryStats(){const results=await Promise.all([db.from('place_stories').select('id',{count:'exact',head:true}),db.from('place_stories').select('id',{count:'exact',head:true}).eq('status','active'),db.from('place_stories').select('id',{count:'exact',head:true}).eq('status','removed'),getStories(1,0,undefined,true)]);results.slice(0,3).forEach(checked);return{totalStories:results[0].count||0,activeStories:results[1].count||0,removedStories:results[2].count||0,reportedStories:results[3].total};}
 return{getStories,getStoryById,getStoryReports,getStoryStats,getReportedStories:(limit=50,offset=0)=>getStories(limit,offset,undefined,true)};
}
